version: '3.9'
services:
  db:
    image: jnsousa/postgres:12.8
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - jnsdev-network
  booklabs:
    image: jnsousa/booklabs
    restart: always
    build: .
    working_dir: /booklabs
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/bookdb
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
        - jnsdev-network
networks:
  jnsdev-network:
    driver: bridge