server:
  port: 8080
spring:
  sql:
    init:
      mode: never
  application:
    name: booklabs
  jpa:
    open-in-view: false
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookdb}
    hikari:
      poolName: Hikari
      auto-commit: false
